import {
  Bell,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  ClipboardList,
  HardHat,
  Headset,
  ListChecks,
  type LucideIcon,
  MessagesSquare,
  Network,
  Radar,
  Send,
  Settings,
  SquareKanban,
  Users,
  UsersRound,
} from "lucide-react";

import type { IconName } from "@/lib/nav";

export const NAV_ICONS: Record<IconName, LucideIcon> = {
  today: CalendarCheck,
  tasks: ListChecks,
  dealFinder: Radar,
  alerts: Bell,
  pipeline: SquareKanban,
  people: Users,
  companies: Building2,
  properties: Building,
  analyze: Calculator,
  outreach: Send,
  calendar: Calendar,
  network: Network,
  receptionist: Headset,
  settings: Settings,
  projects: HardHat,
  requests: ClipboardList,
  community: UsersRound,
  messages: MessagesSquare,
};
